# Generated by Django 3.2.7 on 2022-01-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_inputs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inputs',
        ),
    ]
