# Generated by Django 3.2.7 on 2022-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
